### ISSUE TITLE
More limited permission

### ISSUE THREAD

**Issue by FranklinYu** [dessant/web-archives#21]
**Is your feature request related to a problem? Please describe.**
My employer don’t like browser extension with `<all_urls>` permission.

**Describe the solution you'd like**
Use [`activeTab`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activeTab_permission) instead of `<all_urls>`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dessant** [comment]
The extension needs to inject scripts in tabs that are not active during a search. Hosts also cannot be fully known in advance, because archive providers may redirect, and the hosts from which the archived pages are served also change frequently and are rotated in the case of some search engines.

**Comment by FranklinYu** [comment]
> The extension needs to inject scripts in tabs that are not active during a search.

I would appreciate if an example of this can be provided so that I don’t have to dig through the entire codebase.

**Comment by dessant** [comment]
I don't have time to offer free consulting for my projects. Feel free to contact me for a quote if you need help with vetting the extension for your workplace.

Alternatively, use Firefox. The extension is part of the Recommended extensions program, and it has already been vetted by Mozilla employees to ask only for permissions that are needed.

**Comment by tomfitzhenry** [comment]
I am also keen on removing extensions that require `<all_urls>`, but I can see why this extension uses it.

If this extension only supported Internet Archive, for example, it would not need `<all_urls>`, since it would just grab the current URL from [tabs.getCurrent()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getCurrent) and open a new tab to `https://archive.org/web/$URL`. It can do all that with just `activeTab`.

However, it looks like some caches such as Bing don't provide a direct URL to the Bing cache, so what this extension does is open a tab to Bing search, search for the URL, and then "click" on the cache link of the first search result. This requires a content script, and as @dessant says, the domains sometimes change, hence why the content script permission has been requested for `<all_urls>`.

@dessant, I suppose support for a wide variety of caches is an important part of the project?

**Comment by dessant** [comment]
Yes, the domains do change and there's also redirection to localized versions. There's also a feature to show a page action when an active or background tab returns certain status codes, which requires `<all_urls>`.

Even if the extension wouldn't already require `<all_urls>`, it would cause disruption to request new host permissions every time a new search engine is added.

**Comment by tomfitzhenry** [comment]
I have created https://addons.mozilla.org/en-US/firefox/addon/one-click-wayback/ for the few people that don't need support for a wide variety of caches, but do want to avoid `<all_urls>`.

I will continue to recommend web-archives to my less paranoid friends. :)
