### ISSUE TITLE
Web Archives has been removed from the Chrome Web Store

### ISSUE THREAD

**Issue by TotalCaesar659** [dessant/web-archives#27]
https://chrome.google.com/webstore/detail/hkligngkgcpcolhcnkgccglchdafcnao

**Comment by dessant** [comment]
I've received this cryptic email from Google, and I'm not sure what it means. They have not sent any previous message regarding Web Archives to the Google account used for publishing on the Chrome Web Store, and the extension dashboard only mentions TAKEN DOWN, without a reason being listed.

It would be expected to list any violations in the takedown email and the dashdoard, but that would be too much to expect from Google. When I visit the contact form for extension developers, it asks me to select a color code combination, which was supposed to be in the takedown email, but it's missing.

So I don't understand why was the extension taken down, and I'm not even allowed to contact Google, because I'm not in possession of the magic color codes that allow me to submit their contact form.

**Comment by dessant** [comment]
Chrome Web Store: Removal notification for Web Archives

Chrome Web Store chromewebstore-noreply@google.com Fri, Mar 26, 2021 at 2:03 PM
To: Armin Sebastian *****@gmail.com


Hi there,

We regret to inform you that your item has been removed from the Chrome Web Store. Please find the details below.

Item name: Web Archives

Item ID: hkligngkgcpcolhcnkgccglchdafcnao

Violation(s):

We have not received an update from you on your Google Chrome item before the expiration of the warning period specified in our earlier email.

Because your item continues to not comply with our policies stated in the previous email, it has now been removed from the Chrome Web Store.



Do you believe this was a mistake?

You can use this [Support Page](https://support.google.com/chrome_webstore/contact/one_stop_support) to learn more about this violation and get in touch with us.

We value developer contributions to the Chrome Web Store, and look forward to helping you bring your item into compliance with our policies.

Thanks,

Chrome Web Store Developer Support


[Developer Terms of Service](https://developer.chrome.com/webstore/terms)
[Program Policies](https://developer.chrome.com/webstore/program_policies)
[Branding Guidelines](https://developer.chrome.com/webstore/branding)

**Comment by dessant** [comment]
![1](https://user-images.githubusercontent.com/7513068/112754431-bbbd6880-8fe4-11eb-80fe-335567c124fd.png)
![2](https://user-images.githubusercontent.com/7513068/112754433-bc55ff00-8fe4-11eb-82ad-71d2b630d07b.png)
![3](https://user-images.githubusercontent.com/7513068/112754434-bcee9580-8fe4-11eb-9175-87b52f410db1.png)

**Comment by dessant** [comment]
I've shared everything so you can all experience how absurd a developer's experience can be when dealing with Google.

I'd encourage everyone to share this issue, otherwise there is close to no chance that Google will fix their broken review process, and reinstate Web Archives.

**Comment by TotalCaesar659** [comment]
ClearURLs [got](https://github.com/ClearURLs/Addon/issues/102) this situation recently, you can contact them.

**Comment by cosify** [comment]
Now available in the Chrome Web Store again

**Comment by TotalCaesar659** [comment]
Great, the issue can be closed then.
P.S. Please check [this PR](https://github.com/dessant/web-archives/pull/28).
