### ISSUE TITLE
To a new user, the intentions of the icons aren't obviousl. Consider tooltips?

### ISSUE THREAD

**Issue by pbarney** [dessant/web-archives#29]
**Is your feature request related to a problem? Please describe.**
In the popup, there is a link icon and a heart icon. It's not clear what the purpose of each is. The purpose of the heart icon becomes clear _after_ clicking on it, but the link icon's purpose is not clear. I had thought that perhaps the link icon was to add the current page to an archive, but I really can't tell what it's suppose to do.

**Describe the solution you'd like**
Would you consider a simple `title` attribute in the icon links to describe their purpose? Additionally, it would be helpful to mention their purpose in the documentation.

**Comment by dessant** [comment]
Thanks for opening the issue, this is definitely a problem.

> I had thought that perhaps the link icon was to add the current page to an archive, but I really can't tell what it's suppose to do.

For now the extension only supports viewing archives, and the URL from the current tab is looked up when you click on a search engine. You can search however for an arbitrary URL instead of the current tab by clicking on the link icon and entering the URL in the input field before clicking on a search engine.

**Comment by dessant** [comment]
All icon buttons now have a title, and keyboard navigation should also work better. These changes will land in the next release. Ref https://github.com/dessant/web-archives/commit/096567a973e74df9ef84268cde8afc47ede82dd2
