### ISSUE TITLE
Duplication of Search Engines

### ISSUE THREAD

**Issue by janteau** [dessant/web-archives#32]
I am experiencing where Wayback Machine (All) and Archive.is (All) are duplicated in both the settings and the menu item.

![Screenshot_2021-08-18_16-41-32](https://user-images.githubusercontent.com/32575346/129969677-5597a276-6fac-4b27-9fbe-bc979ebcf7d1.png)

![Screenshot_2021-08-18_16-42-17](https://user-images.githubusercontent.com/32575346/129969686-db308be1-2c9d-47a4-a99e-7709bb2bcc7a.png)

The duplicated search engines are tied together (unchecking one copy unchecks the other).  This has been replicated to all of my other Firefox sessions that are connected to my Firefox Sync account.  If I remove the extension and reinstall it, the duplicated search engines remain.  Is there a way to delete just the Web Archives extension data without resetting the whole Firefox profile?

**Comment by dessant** [comment]
I'm not sure what is the root cause, but you could clear the extension's sync storage, to bring it to a freshly installed state.

1. Visit `about:debugging#/runtime/this-firefox`
2. Go to Web Archives an click `Inspect`
3. Select the `Console` tab
4. Paste the code below in the console, where the cursor blinks, then press `Enter`

```js
browser.storage.sync.clear()
```

Now you can restart your browser, and the recreated extension settings will hopefully propagate to your other devices after some delay.

**Comment by janteau** [comment]
Thanks @dessant, that fixed it for me!
