### ISSUE TITLE
Open new tab as child of existing tab

### ISSUE THREAD

**Issue by sphh** [dessant/web-archives#57]
I love your add-on. It is not only a time-saver, but often it is the preferred way to get hold of the information I am looking for! Thanks.

**Is your feature request related to a problem? Please describe.**

At the moment, the new tab opened by Web Archives is appended at the end of the existing tabs.

**Describe the solution you'd like**

I would like to have the new tab opened next to the ‘calling’ tab – or even as a child.

**Comment by dessant** [comment]
Let's track this issue here: https://github.com/dessant/web-archives/issues/52

**Comment by sphh** [comment]
Oops, you are right. I could not deduce from the title, that this is the same request!

**Comment by dessant** [comment]
Btw, the feature was there in the past before it got removed, here are some details: https://github.com/dessant/search-by-image/issues/182#issuecomment-1086129664

I'll give it a shot again in the coming months because I have to partially rewrite the extension anyway due to the Manifest V3 deadline in Chrome.
